#pragma once
#include <fstream>
#include <iostream>
#include "structures.h"
void ReadFromFile();
void saveusersinfo();
void load_subsc_data();
void save_subsc_data();
void save_user_subsc();
void load_user_subsc();
void read_stations();
void stations2file();
void loadRideHist();
void save_rides_to_file();
